//Student
export const STUDENT_LOGIN = "STUDENT_LOGIN";
export const STUDENT_SIGNUP = "STUDENT_SIGNUP";
export const STUDENT_DETAILS = "STUDENT_DETAILS";
export const STUDENT_UPDATE_PICTURE = "STUDENT_UPDATE_PICTURE";
export const STUDENT_DELETE_PICTURE = "STUDENT_DELETE_PICTURE";
export const STUDENT_UPDATE_PROFILE = "STUDENT_UPDATE_PROFILE";
export const STUDENT_FORM_LIST = "STUDENT_FORM_LIST";
export const STUDENT_CREATE_FORM = "STUDENT_CREATE_FORM";
export const STUDENT_DELETE_FORM = "STUDENT_DELETE_FORM";

//Institute Personnel
export const INSTITUTE_PERSONNEL_LOGIN = "INSTITUTE_PERSONNEL_LOGIN";
export const INSTITUTE_PERSONNEL_SIGNUP = "INSTITUTE_PERSONNEL_SIGNUP";

//Maintenance
export const MAINTENANCE_DETAILS = "MAINTENANCE_DETAILS";
export const MAINTENANCE_UPDATE_PICTURE = "MAINTENANCE_UPDATE_PICTURE";
export const MAINTENANCE_DELETE_PICTURE = "MAINTENANCE_DELETE_PICTURE";
export const MAINTENANCE_UPDATE_PROFILE = "MAINTENANCE_UPATE_PROFILE";
export const MAINTENANCE_FORM_LIST = "MAINTENANCE_FORM_LIST";
export const MAINTENANCE_STAGE = "MAINTENANCE_STAGE";

//Manager
export const MANAGER_DETAILS = "MANAGER_DETAILS";
export const MANAGER_UPDATE_PICTURE = "MANAGER_UPDATE_PICTURE";
export const MANAGER_DELETE_PICTURE = "MANAGER_DELETE_PICTURE";
export const MANAGER_UPDATE_PROFILE = "MANAGER_UPDATE_PROFILE";
export const MANAGER_FORM_LIST = "MANAGER_FORM_LIST";
export const STUDENT_LIST = "STUDENT_LIST";
export const MAINTENANCE_LIST = "MAINTENANCE_LIST";
export const MANAGER_LIST = "MANAGER_LIST";

//User
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CONTACT = "CONTACT";
