//Auth
export const LOGIN= "LOGIN"

export const FORGOT_PASSWORD = "FORGOT_PASSWORDL"
export const VERIFY_OTP_FOR_FORGOT_PASSWORD = "VERIFY_OTP_FOR_FORGOT_PASSWORD"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"

export const SIGNUP = "SIGNUP"
export const SIGNUP_OTP = "SIGNUP_OTP"
export const VERIFY_OTP_FOR_SIGNUP = "VERIFY_OTP_FOR_SIGNUP"

//User
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const USER_DETAILS = "USER_DETAILS";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const DELETE_PROFILE_PICTURE = "DELETE_PROFILE_PICTURE";

